export const MESSAGING_CONVERSATION_REPOSITORY = Symbol('MESSAGING_CONVERSATION_REPOSITORY');
export const MESSAGING_MESSAGE_REPOSITORY = Symbol('MESSAGING_MESSAGE_REPOSITORY');
export const MESSAGING_TELEGRAM_OFFSET_STORE = Symbol('MESSAGING_TELEGRAM_OFFSET_STORE');
