export const MESSAGING_TELEGRAM_CLIENT = Symbol('MESSAGING_TELEGRAM_CLIENT');
export const MESSAGING_REPLY_GENERATOR = Symbol('MESSAGING_REPLY_GENERATOR');
export const MESSAGING_DOMAIN_EVENT_PUBLISHER = Symbol('MESSAGING_DOMAIN_EVENT_PUBLISHER');
export const MESSAGING_CLOCK = Symbol('MESSAGING_CLOCK');
export const MESSAGING_ID_GENERATOR = Symbol('MESSAGING_ID_GENERATOR');

export const LIST_CONVERSATIONS_USE_CASE = Symbol('LIST_CONVERSATIONS_USE_CASE');
export const GET_CONVERSATION_USE_CASE = Symbol('GET_CONVERSATION_USE_CASE');
export const SEND_MESSAGE_TO_CHAT_USE_CASE = Symbol('SEND_MESSAGE_TO_CHAT_USE_CASE');
export const PROCESS_TELEGRAM_UPDATES_USE_CASE = Symbol('PROCESS_TELEGRAM_UPDATES_USE_CASE');
